import type { HTMLAttributes, ReactNode } from 'react';
import { Logo } from './Logo';
import { Seal } from './Seal';
import { cn } from '../cn';

export interface CertificateSheetProps extends Omit<HTMLAttributes<HTMLDivElement>, 'title'> {
  studentName?: string;
  levelName?: string;
  academicYear?: string;
  /** Auto-generated by the API as L4-1447-0001 unless one is supplied. */
  serial?: string;
  issuedOn?: string;
  headTeacher?: string;
  title?: string;
  /** Overrides the default body wording. */
  body?: ReactNode;
  scale?: number;
  logoSrc?: string;
}

/** A4 portrait RTL certificate. Ivory paper, gold rules, long-form type.
 *  This is the one surface where gold leads.
 *
 *  NOTE: the printed wording is still undecided by the institute
 *  (backend/agent/progress.md, "Still open" #2). The default body below is a
 *  placeholder carried over from the design system — confirm it with the head
 *  teacher before this sheet is issued to anyone. */
export function CertificateSheet({
  studentName,
  levelName,
  academicYear,
  serial,
  issuedOn,
  headTeacher,
  title = 'شهادة إتمام مستوى',
  body,
  scale = 1,
  logoSrc,
  className,
  ...rest
}: CertificateSheetProps) {
  return (
    <div
      style={{
        transform: scale !== 1 ? `scale(${scale})` : undefined,
        transformOrigin: 'top right',
      }}
      className={cn(
        'ef-print-sheet box-border w-[210mm] min-h-[297mm] border border-gold-200 bg-paper px-[16mm] py-[18mm]',
        'font-longform text-ink-900',
        className,
      )}
      {...rest}
    >
      <div className="grid h-full justify-items-center gap-[10mm] border-2 border-gold-500 px-[12mm] py-[14mm] text-center outline outline-gold-200 outline-offset-4">
        <Logo variant="mark" height={90} src={logoSrc} />

        <div>
          <div className="font-sans text-sm text-gold-700">دورات الفرقان التثقيفية</div>
          <h1 className="mt-1.5 font-longform text-[30pt] text-teal-700">{title}</h1>
        </div>

        <div className="h-0.5 w-3/5 bg-gold-300" />

        <p className="m-0 max-w-[150mm] text-[14pt] leading-[1.95]">
          {body ?? (
            <>
              تشهد إدارة دورات الفرقان التثقيفية بأن الطالب/الطالبة{' '}
              <strong className="text-teal-700">{studentName}</strong> قد أتمّ{' '}
              <strong>{levelName}</strong> للعام الدراسي{' '}
              <span className="ef-num">{academicYear}</span> بنجاح، وقد مُنح هذه الشهادة تقديرًا
              لاجتهاده.
            </>
          )}
        </p>

        <Seal serial={serial} />

        <div className="mt-auto flex w-full items-end justify-between font-sans text-xs text-ink-500">
          <div className="text-start">
            <div className="ef-num">رقم الشهادة: {serial}</div>
            <div className="ef-num">تاريخ الإصدار: {issuedOn}</div>
          </div>
          <div className="text-center">
            <div className="mb-1 w-[46mm] border-b border-gold-300" />
            <div>{headTeacher ?? 'مدير المعهد'}</div>
          </div>
        </div>
      </div>
    </div>
  );
}
