/* The certificate shapes this feature renders, mirrored from the API
   (src/assessment/promotion.service.ts). */

/** A student whose level result makes them ready to certify (§4.5). */
export interface CertifiableStudent {
  studentId: string;
  studentName: string;
  enrollmentId: string;
  levelId: number;
  levelCode: string;
  decision: string;
}

export interface Certificate {
  id: string;
  studentId: string;
  studentName: string;
  levelId: number;
  levelCode: string;
  serialNo: string | null;
  issuedAt: string;
  revokedAt: string | null;
  revokeReason: string | null;
}

/** Everything a printed sheet needs, returned by reprint. Recording a copy is
 *  the point of reprint, so this only ever comes from that call (R19 / §4.5). */
export interface CertificatePrintPayload {
  certificateId: string;
  serialNo: string | null;
  studentName: string;
  studentCode: string;
  levelCode: string;
  levelNameAr: string;
  instituteNameAr: string;
  branchNameAr: string | null;
  hijriYear: number | null;
  issuedAt: string;
  issuedByName: string;
  /** 1 is the original issue; 2 and above are reprints. */
  copyNumber: number;
  notes: string | null;
}

/** The fields issuing needs; the serial is generated by the API when omitted. */
export interface IssueCertificatePayload {
  studentId: string;
  levelId: number;
  enrollmentId: string | null;
}
